export type EvidenceClass = 'measured' | 'user_estimate' | 'scenario_assumption';
export interface EmissionFactor { id:string; name:string; value:number; unit:string; source:string; effectiveDate:string; methodologyVersion:string; note:string; }
export interface PUEResult { pue:number; itEnergyKWh:number; facilityEnergyKWh:number; overheadKWh:number; overheadPercentage:number; isValid:boolean; error?:string; }
export interface EnergySavingsResult { annualKWhSaved:number; dailyKWhSaved:number; isValid:boolean; error?:string; }
export interface CarbonEmissionsResult { operationalKgCO2e:number; operationalTonsCO2e:number; avoidedKgCO2e?:number; avoidedTonsCO2e?:number; emissionFactorUsed:number; emissionFactorSource:string; isValid:boolean; error?:string; }
export interface HardwareLifecycleResult { deviceCount:number; baselineLifespanYears:number; extendedLifespanYears:number; baselineAnnualReplacements:number; extendedAnnualReplacements:number; annualDevicesSaved:number; avoidedEmbodiedKgCO2eAnnual:number; avoidedEmbodiedTonsCO2eAnnual:number; avoidedEWasteKgAnnual:number; avoidedEWasteTonsAnnual:number; isValid:boolean; error?:string; }
export interface ScenarioInputs { facilityName:string; itEquipmentEnergyKWh:number; totalFacilityEnergyKWh:number; targetPUE:number; gridEmissionFactorId:string; backupGeneratorHoursPerYear:number; generatorFuelRateLitersPerHour:number; renewablePPAFraction:number; serverCount:number; wattsSavedPerServer:number; operatingHoursPerDay:number; deviceCount:number; baselineLifespanYears:number; extendedLifespanYears:number; embodiedCarbonPerDeviceKg:number; deviceWeightKg:number; evidenceClasses:Record<string,EvidenceClass>; }
export interface ScenarioCompleteResult { scenarioId:string; timestamp:string; pue:PUEResult; energySavings:EnergySavingsResult; baselineCarbon:CarbonEmissionsResult; optimizedCarbon:CarbonEmissionsResult; lifecycle:HardwareLifecycleResult; netAvoidedCarbonTonsAnnual:number; metadata:{methodologyVersion:string; calculationEngine:string; author:string}; }
export interface AIAdvisorRequest { scenarioInputs:ScenarioInputs; deterministicResults:ScenarioCompleteResult; focusArea?:'pue_optimization'|'grid_integration'|'lifecycle_circularity'|'national_policy'; }
export interface AIAdvisorResponse { strategicRecommendations:Array<{title:string;priority:'high'|'medium'|'low';feasibility:'immediate'|'medium_term'|'policy_dependent';description:string;governanceMechanism:string}>; gridAndEnergyAnalysis:string; hardwareLifecycleAdvice:string; policyAlignmentInsight:string; evidenceIntegrityNotice:string; modelTimestamp:string; }
